﻿
@url = https://localhost:5000 
@reservationId = 44332e23-5def-4705-a7ad-1e393586e5d3
@machineId = 00000000-0000-0000-0000-000000000001

###
GET  {{url}}
###
GET  {{url}}/reservations
###
GET  {{url}}/reservations/{{reservationId}}
 
###
POST {{url}}/reservations
Content-Type: application/json

{
  "machineId": "{{machineId}}",
  "date": "2022-11-22", 
  "employeeName": "string",
  "hour": "12"
}
###
PUT {{url}}/reservations/{{reservationId}}
Content-Type: application/json    

{   
"hour": "13"   
}

###
DELETE  {{url}}/reservations/{{reservationId}}
 