﻿
@url = https://localhost:5000 
@reservationId = 5b20554b-2869-44d3-8549-209dec990903
@parkingspotId = 00000000-0000-0000-0000-000000000001 
#@reservationId = 00000000-0000-0000-0000-000000000001
  
###
GET  {{url}}
###
GET  {{url}}/reservations
###
GET  {{url}}/reservations/{{reservationId}}
 
###
POST {{url}}/reservations
Content-Type: application/json

{
"parkingSpotId" : "00000000-0000-0000-0000-000000000005",
"employeeName" : "JohnSzop",
"licencePlate": "123456",
"date": "2022-11-19"
}
###
PUT {{url}}/reservations/{{reservationId}}
Content-Type: application/json   

{  

"licencePlate": "222333"  

}
###
DELETE  {{url}}/reservations/{{reservationId}}
 