﻿
@url = https://localhost:5000 
@reservationId = 0b38c55d-d96c-4a2a-985c-042cb32d6a75
@machineId = 00000000-0000-0000-0000-000000000001

###
GET  {{url}}
###
GET  {{url}}/reservations
###
GET  {{url}}/reservations/{{reservationId}}
 
###
POST {{url}}/reservations
Content-Type: application/json

{
  "machineId": "{{machineId}}",
  "date": "2023-01-13", 
  "employeeName": "string",
  "hour": "13"
}
###
PUT {{url}}/reservations/{{reservationId}}
Content-Type: application/json    

{   
"hour": "13"   
}

###
DELETE  {{url}}/reservations/{{reservationId}}
 