 
@url = https://localhost:5000
@reservationId = 64af2ba8-00b4-40d2-89ce-5e0d49bad694
@machineId = 00000000-0000-0000-0000-000000000002
@test = https://localhost:5000/machines

###
POST {{url}}/users
Content-Type: application/json

{ 
  "email": "szop@szio.pl", 
  "userName": "Szop1",  
  "password": "zabezpieczmnie123", 
  "fullName": "Roman G", 
  "role": "employee"
}

###
GET  {{url}}

###
GET  {{url}}/machines

###
POST {{url}}/machines/{{machineId}}/reservations/employee
Content-Type: application/json

{ 
  "date": "2023-01-25", 
  "employeeName": "employeeRest",
  "hour": "10"
}
###
POST {{url}}/machines/{{machineId}}/reservations/service
Content-Type: application/json

{
  "date": "2023-02-03", 
  "hour": "13"
}
###
PUT {{url}}/machines/reservations/{{reservationId}}
Content-Type: application/json    

{   
"hour": "11"   
}

###
DELETE  {{url}}/reservations/{{reservationId}}
 