 
@url = https://localhost:5000
@reservationId = 64af2ba8-00b4-40d2-89ce-5e0d49bad694
@machineId = 00000000-0000-0000-0000-000000000002
@test = https://localhost:5000/machines
@accesstoken2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiYzhhNWVkNS05YTJmLTRiNWEtOTJkZi1jNGE3YzkyMTk1MjYiLCJ1bmlxdWVfbmFtZSI6ImJjOGE1ZWQ1LTlhMmYtNGI1YS05MmRmLWM0YTdjOTIxOTUyNiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6InVzZXIiLCJuYmYiOjE2NzU3ODgxNDIsImV4cCI6MTY3NTc5MTc0MiwiaXNzIjoicHJvZHVjdGlvbnNjaGVkdWxlci1pc3N1ZXIiLCJhdWQiOiJwcm9kdWN0aW9uc2NoZWR1bGVyLWF1ZGllbmNlIn0.E_jawqeD2F_Tl9OW-87CgVRkNYJCHgMRz5Qrf_LUKdE

###
POST {{url}}/users
Content-Type: application/json

{ 
  "email": "szop@szio.pl", 
  "userName": "Szop1",  
  "password": "zabezpieczmnie123", 
  "fullName": "Roman G", 
  "role": "user"
}

###
# @name sign_in
POST {{url}}/users/sign-in
Content-Type: application/json

{ 
  "email": "szop@szio.pl", 
  "password": "zabezpieczmnie123" 
}

###
@accessToken = {{sign_in.response.body.$.accessToken}}


###
GET  {{url}}/machines

###
GET  {{url}}/users

###
GET  {{url}}/users/bc8a5ed5-9a2f-4b5a-92df-c4a7c9219526

###
GET  {{url}}/users/jwt
 
### 
GET  {{url}}/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3OGE1MjYyZS1kYzNjLTQ3ZmYtOTA2MS00YTc1Mjk3MjFkOWIiLCJ1bmlxdWVfbmFtZSI6Ijc4YTUyNjJlLWRjM2MtNDdmZi05MDYxLTRhNzUyOTcyMWQ5YiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6InVzZXIiLCJuYmYiOjE2NzU4NDkxODAsImV4cCI6MTY3NTg1Mjc4MCwiaXNzIjoicHJvZHVjdGlvbnNjaGVkdWxlci1pc3N1ZXIiLCJhdWQiOiJwcm9kdWN0aW9uc2NoZWR1bGVyLWF1ZGllbmNlIn0.3OWMXM3KaXKgYa1WUKajjBwim69qEGdOmWM3zjCwzAY

###
POST {{url}}/machines/{{machineId}}/reservations/employee
Content-Type: application/json

{ 
  "date": "2023-02-03", 
  "employeeName": "employeeRest",
  "hour": "10"
}
###
POST {{url}}/machines/{{machineId}}/reservations/service
Content-Type: application/json

{
  "date": "2023-02-03", 
  "hour": "13"
}
###
PUT {{url}}/machines/reservations/{{reservationId}}
Content-Type: application/json    

{   
"hour": "11"   
}

###
DELETE  {{url}}/reservations/{{reservationId}}
 